apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: omfr6yqae-dotnet-basic
  janus-idp.io/tekton: omfr6yqae-dotnet-basic
  backstage.io/kubernetes-id: omfr6yqae-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: omfr6yqae-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
